[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
	"cd app && python -m pip install --upgrade pip setuptools wheel",
	"cd app && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd app && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
