[build]
builder = "DOCKERFILE"
dockerfilePath = "nextjs-app/Dockerfile"

[deploy]
startCommand = "sh -c 'npm start'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
